import { ClientLayout } from './ClientLayout'

const metadata = {
  title: 'بازار اینترنتی دارتیل',
  description: 'Generated by create-nx-workspace',
}

const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => (
  <html lang="en" dir="rtl">
    <head>
      <link href={process.env.NEXT_PUBLIC_CDN} rel="preconnect" />
      <link href={process.env.NEXT_PUBLIC_GATEWAY} rel="preconnect" />
      <link href="/icons/favicon.ico" rel="shortcut icon" />

      <link href="/manifest.json" rel="manifest" />
      <meta charSet="utf-8" />
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta
        content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, maximum-scale=1"
        name="viewport"
      />
      <link
        href="/icons/splash/iphone5_splash.png"
        media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
        rel="apple-touch-startup-image"
      />
      <link
        href="/icons/splash/iphone6_splash.png"
        media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
        rel="apple-touch-startup-image"
      />
      <link
        href="/icons/splash/iphoneplus_splash.png"
        media="(device-width: 621px) and (device-height: 1104px) and (-webkit-device-pixel-ratio: 3)"
        rel="apple-touch-startup-image"
      />
      <link
        href="/icons/splash/iphonex_splash.png"
        media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
        rel="apple-touch-startup-image"
      />
      <link
        href="/icons/splash/iphonexr_splash.png"
        media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)"
        rel="apple-touch-startup-image"
      />
      <link
        href="/icons/splash/iphonexsmax_splash.png"
        media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)"
        rel="apple-touch-startup-image"
      />
      <link
        href="/icons/splash/ipad_splash.png"
        media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
        rel="apple-touch-startup-image"
      />
    </head>
    <body>
      <ClientLayout>{children}</ClientLayout>
    </body>
  </html>
)

export { metadata }
export default RootLayout
