import { ClientLayout } from './ClientLayout'

const metadata = {
  title: 'Welcome to qcommerce',
  description: 'Generated by create-nx-workspace',
}

const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => (
  <html lang="en" dir="rtl">
    <head>
      <link href={process.env.NEXT_PUBLIC_CDN} rel="preconnect" />
      <link href={process.env.NEXT_PUBLIC_GATEWAY} rel="preconnect" />
      <link href="/icons/favicon.png" rel="shortcut icon" />

      <link href="/manifest.json" rel="manifest" />
      <meta charSet="utf-8" />
      <meta
        content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, maximum-scale=1"
        name="viewport"
      />
    </head>
    <body>
      <ClientLayout>{children}</ClientLayout>
    </body>
  </html>
)

export { metadata }
export default RootLayout
